### PR TITLE
Ensure only ginkgo v2 for DescribeTable support

### PR DESCRIPTION
**Pull request by martinkennelly**
PR #4907 used ginkgo v1 to utilize DescribeTable
but we already moved away from that as seen in
PR #4749

Also, executed 'go mod tidy && go mod vendor'
as go mod file was stale.

Follow up work is required to detect this scenario in CI.
I missed the the changes in #4749 during my rebase.

### CODE REVIEW

**Comment by martinkennelly** [comment]
Looks like a test is hanging somewhere after switching to ginkgo v2 `DescribeTable`.  Investigating.

**Review by tssurya — COMMENTED** [review]
the main test file changes lgtm
but why is the vendored code changing without any changes to go.mod/go.sum ? go tidy was done?

**Comment by tssurya** [comment]
will circle back when CI is green

**Comment by trozet** [comment]
this failure looks new:

```
Summarizing 1 Failure:
  [FAIL] e2e egress IP validation Network Segmentation: IPv4 L3 role primary [It] [OVN network] Should validate the egress IP SNAT functionality against host-networked pods
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/egressip.go:1051
```
https://github.com/ovn-kubernetes/ovn-kubernetes/actions/runs/12394641727/job/34600070380?pr=4924

**Comment by martinkennelly** [comment]
Lesson here is never mix v1 and v2 ginkgo. Use one or the other.
 The v1 tests (DescribeTables) weren't being used at all after we switched to v2.

**Comment by martinkennelly** [comment]
Ginkgo uses reflect to infer the test type and they are different for v1 and v2 and that explains why it ignored them.

**Comment by martinkennelly** [comment]
I cannot reproduce the test failure locally for the e2e error that Tim mentioned. 
Inspecting the KinD logs for that test run to look for anything abnormal.

**Comment by martinkennelly** [comment]
We had no issues with ginkgo v1 and v2 conflicts within the e2e test that failed. It seems like a flake. I am looking into the ovnkube logs.

**Comment by martinkennelly** [comment]
E2Es seem fine.
There are flakes and I will create / update issues tomorrow.

**Review by trozet — APPROVED** [review]

**Pull request merged**
