### PR TITLE
WIP check main branch state

### PR DESCRIPTION
**Pull request by oshoval**
want to see if we have same storage removal problem as here
https://github.com/kubevirt/ipam-extensions/pull/78#issuecomment-2543893334

## 📑 Description

Fixes #

## ✅ Checks

- [ ] My code requires changes to the documentation
- [ ] if so, I have updated the documentation as required
- [ ] My code requires tests
- [ ] if so, I have added and/or updated the tests as required
- [ ] All the tests have passed in the CI

### CODE REVIEW

**Comment by oshoval** [comment]
Researched here by @ashokpariya0, thanks
https://github.com/kubevirt/cluster-network-addons-operator/pull/1927#issuecomment-2543910050
lets discuss please the desired solution

cc @maiqueb @qinqon fyi please
Thanks

**Comment by ashokpariya0** [comment]
The "Free up disk space" step ([link](https://github.com/ovn-kubernetes/ovn-kubernetes/actions/runs/12339597663/workflow?pr=4914#L295)) is now broken with the main branch. Please check the logs for this PR at [link](https://github.com/ovn-kubernetes/ovn-kubernetes/actions/runs/12339597663/job/34436357534?pr=4914).

It seems that ubuntu-latest now points to Ubuntu 24.04 instead of Ubuntu 22.04. However, this change is not yet reflected on the [runner-images repository](https://github.com/actions/runner-images), where it still shows ubuntu-latest as 22.04.

To address this, we either need to remove unnecessary installed packages (as outlined in the [workflow file](https://github.com/ovn-kubernetes/ovn-kubernetes/blob/master/.github/workflows/test.yml#L295-L304)) or switch to using ubuntu:22.04 instead of ubuntu-latest. What are your thoughts on this?

**Comment by ashokpariya0** [comment]
I tried using ubuntu-22.04, and it worked. For reference, here is the PR with change:
https://github.com/kubevirt/cluster-network-addons-operator/pull/1945

**Comment by martinkennelly** [comment]
I also tried it for our CI and it works by reverting to 22.04.

**Pull request closed without merging**
